name: Build and Deploy API and UI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build and publish API
        run: dotnet publish ./KwestKarz-API/KwestKarz/KwestKarz.csproj -c Release -o ./publish

      - name: Upload API build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: ./publish

      - name: Upload API source code
        uses: actions/upload-artifact@v4
        with:
          name: api-source
          path: ./KwestKarz-API

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Download API build artifacts
        uses: actions/download-artifact@v4
        with:
          name: api-artifact
          path: ./api-artifact

      - name: Download API source code
        uses: actions/download-artifact@v4
        with:
          name: api-source
          path: ./api-source

      - name: Upload API build to Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          source: "./api-artifact/*"
          target: "/home/${{ secrets.DROPLET_USER }}/kwestkarz-app/"

      - name: Upload API source to Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          source: "./api-source/*"
          target: "/home/${{ secrets.DROPLET_USER }}/kwestkarz-src/"

      - name: Run migration and restart API service
        uses: appleboy/ssh-action@v0.1.7
        envs: GOOGLE_EMAIL_ADDR,GOOGLE_SMTP_PASSWORD,DEPLOY_SUDO_PASSWORD
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          script: |
            echo "Stopping service..."
            echo "$DEPLOY_SUDO_PASSWORD" | sudo -S systemctl stop kwestkarz.service || true
            echo "Installing dotnet-ef locally..."
            export DOTNET_ROOT=~/.dotnet
            export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools:~/.dotnet/tools
            mkdir -p ~/.dotnet/tools
            dotnet tool install dotnet-ef --tool-path ~/.dotnet/tools || true
            echo "Running migration..."
            export ConnectionStrings__KwestKarzDb="Host=localhost;Database=kwestkarz;Username=kwestkarz_user;Password=htrv6gpl1234!@#$"
            export google__email="$GOOGLE_EMAIL_ADDR"
            export google__password="$GOOGLE_SMTP_PASSWORD"
            cd /home/${{ secrets.DROPLET_USER }}/kwestkarz-src/KwestKarz/KwestKarz
            ~/.dotnet/tools/dotnet-ef database update --project KwestKarz.csproj
            echo "Starting service..."
            echo "$DEPLOY_SUDO_PASSWORD" | sudo -S systemctl start kwestkarz.service
