name: Build and Deploy API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build and publish API
        run: dotnet publish ./KwestKarz/KwestKarz.csproj -c Release -o ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: api-artifact
          path: ./publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: api-artifact

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            rm -rf /home/wwestlake/kwestkarz-app/*
            mkdir -p /home/wwestlake/kwestkarz-app/
            cp -r ./publish/* /home/wwestlake/kwestkarz-app/
            sudo systemctl restart kwestkarz.service
