name: Build and Deploy API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build and publish API
        run: dotnet publish ./KwestKarz/KwestKarz.csproj -c Release -o ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api-artifact
          path: ./publish
