name: Build and Deploy API and Portal

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: ./KwestKarz-Portal
        run: npm ci

      - name: Build frontend
        working-directory: ./KwestKarz-Portal
        run: npm run build
        env:
          VITE_API_BASE_URL: https://kwestkarz.lagdaemon.com/api

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: portal-artifact
          path: ./KwestKarz-Portal/dist

      - name: Build and publish API
        run: dotnet publish ./Kwestkarz-API/KwestKarz/KwestKarz.csproj -c Release -o ./publish

      - name: Upload API build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: portal-artifact
          path: portal-artifact

      - name: Download API artifacts
        uses: actions/download-artifact@v4
        with:
          name: api-artifact
          path: api-artifact

      - name: Upload source code to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          source: "./Kwestkarz-API/**"
          target: "/home/${{ secrets.DROPLET_USER }}/kwestkarz-src/api-source"

      - name: Debug portal artifact contents
        run: ls -R portal-artifact

      - name: Debug API artifact contents
        run: ls -R api-artifact

      - name: Copy frontend files to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          source: "portal-artifact/*"
          target: "/var/www/html"
      
      - name: Copy API files to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          source: "api-artifact/**"
          target: "/home/${{ secrets.DROPLET_USER }}/"
      
      - name: Deploy to server via SSH 
        uses: appleboy/ssh-action@v0.1.7
        env:
          DEPLOY_SUDO_PASSWORD: ${{ secrets.DEPLOY_SUDO_PASSWORD }}
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          script: |
            bash /home/${{ secrets.DROPLET_USER }}/deploy-api.sh "${{ secrets.DEPLOY_SUDO_PASSWORD }}" "${{ secrets.CONNECTION_STRING }}" "${{ secrets.GOOGLE_EMAIL_ADDR }}" "${{ secrets.GOOGLE_SMTP_PASSWORD }}" "${{ secrets.DROPLET_USER }}"
