name: Build and Deploy API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build and publish API
        run: dotnet publish ./KwestKarz/Kwestkarz-API/KwestKarz.csproj -c Release -o ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: ./publish

      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: api-source
          path: ./KwestKarz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: api-artifact
          path: ./api-artifact

      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: api-source
          path: ./api-source

      - name: Upload build artifacts to Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          source: "./api-artifact/*"
          target: "/home/${{ secrets.DROPLET_USER }}/kwestkarz-app/"

      - name: Upload source code to Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          source: "./api-source/*"
          target: "/home/${{ secrets.DROPLET_USER }}/kwestkarz-src/"

      - name: Run schema migration and start service
        uses: appleboy/ssh-action@v0.1.7
        env:
          DEPLOY_SUDO_PASSWORD: ${{ secrets.DEPLOY_SUDO_PASSWORD }}
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          google_email_addr: ${{ secrets.GOOGLE_EMAIL_ADDR }}  
          google_smtp_password: ${{ secrets.GOOGLE_SMTP_PASSWORD }}
          port: 22
          script: |
            echo "Stopping service..."
            echo "$DEPLOY_SUDO_PASSWORD" | sudo -S systemctl stop kwestkarz.service || true
            echo "Installing dotnet-ef locally..."
            export DOTNET_ROOT=~/.dotnet
            export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools:~/.dotnet/tools
            mkdir -p ~/.dotnet/tools
            dotnet tool install dotnet-ef --tool-path ~/.dotnet/tools || true
            echo "Running migration..."
            export ConnectionStrings__KwestKarzDb="Host=localhost;Database=kwestkarz;Username=kwestkarz_user;Password=htrv6gpl1234!@#$"
            export google__email="${{ secrets.GOOGLE_EMAIL_ADDR }}"
            export google__password="${{ secrets.GOOGLE_SMTP_PASSWORD }}"
            cd /home/${{ secrets.DROPLET_USER }}/kwestkarz-src/api-source
            ~/.dotnet/tools/dotnet-ef database update --project KwestKarz.csproj
            echo "Cleaning up source..."
            # rm -rf /home/${{ secrets.DROPLET_USER }}/kwestkarz-src
            echo "Starting service..."
            echo "$DEPLOY_SUDO_PASSWORD" | sudo -S systemctl start kwestkarz.service
